# https://taskfile.dev

version: "3"

dotenv: [".env"]

tasks:
  test:
    desc: run all tests
    cmds:
      - go test ./...

  tag:
    desc: tag the current commit
    cmds:
      - git tag -a v0.0.2 -m "updates"
      - git push origin v0.0.2

  release:
    desc: release binary to github
    cmds:
      - goreleaser release --clean --skip=validate
